name: flutter_plugin_tef_integration
description: Flutter plugin TEF Integration
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: "3.16.9"

dependencies:
  flutter:
    sdk: flutter

  ideploy_package:
    git:
      url: git@github.com:Ideploy22/flutter-lib-common-packages.git
      ref: 1.2.0

  plugin_platform_interface: ^2.1.8

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  plugin:
    platforms:
      android:
        package: br.ideploy.tef.integration.flutter_plugin_tef_integration
        pluginClass: FlutterPluginTefIntegrationPlugin